[package]
name = "mesh-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.24.1"
thiserror = "1.0.43"
noise = "0.8.2"
rand = "0.8.5"
byteorder = "1.4.3"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# We're implementing glTF export directly against the spec, so we don't need these
# gltf = "1.3.0" 
# gltf-json = "1.3.0"
