[package]
name = "mesh-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.25.0"    # Linear algebra and math library for graphics
thiserror = "1.0"  # Error handling
gltf = { version = "1.4", features = ["KHR_lights_punctual", "extras", "names", "utils"] }
base64 = "0.21"
byteorder = "1.5"
